# -*- coding: utf-8 -*-
"""process.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7X4kuxrbYlh2640vJHubgsnv33MLvr4
"""

import pandas as pd

sheet_names = [
  'homologacion_pais',
  'homologacion_rating',
  'rating_empresa',
  'rating_soberano'
]
data = pd.read_excel("data/data.xlsx", sheet_names, na_values=["null"])

def iterateForData(cb):
  for sheet_name, content in data.items():
    cb(sheet_name, content)

def printDFInformation(sheet_name, content):
  print(f'{sheet_name}')
  print('-' * 20)
  print(content.isnull().sum())
  print('')
  print('*' * 20)
  print('')

iterateForData(printDFInformation)

def dropColsOfDF(sheet_name, content):
  to_drop = {
    'homologacion_pais': [
      'cod_pais',
    ],
    'homologacion_rating': [
      'orden_agencia',
      'agencia',
    ],
    'rating_empresa': [
      'tipo',
    ],
    'rating_soberano': [
      'ticker',
      'region',
    ],
  }

  for sheet_name_del, col_del in to_drop.items():
    if sheet_name == sheet_name_del:
      content.drop(columns=col_del, inplace=True)

iterateForData(dropColsOfDF)

def replaceStr(sheet_name, content):
  if sheet_name == 'rating_soberano':
    content.replace(to_replace=r'u$', value='', regex=True, inplace=True)
    content.replace(to_replace=r'^[^(?!A)|(?!B)|(?!C)|(?!D)|(?!E)].*', value='', regex=True, inplace=True)

iterateForData(replaceStr)

def toUpperCase(sheet_name, content):
  for column_name in content:
    content[column_name] = content[column_name].astype(str).str.upper()

iterateForData(toUpperCase)

def printDFInformation(sheet_name, content):
  print(f'{sheet_name}')
  print('-' * 20)
  print(content.fillna('').isnull().sum())
  print('')
  print('*' * 20)
  print('')
  
iterateForData(printDFInformation)

for sheet_name, content in data.items():
  content.fillna('').to_csv(f'data/out{sheet_name}.csv', sep='|')